### ISSUE TITLE
Error on OSX 

### ISSUE THREAD

**Issue by granludo** [jimy-byerley/pymadcad#36]
Hi, 
on the last OSX version 11.6 on Intel, I made a clean install of Python, Cython, and PyMadCad. 
I tried running the sample program (here in github) and I get this error ( the same file works fine on Ubuntu)
Thanks in advance
Marc
```
ludo@ludo-macbook gcode % python3 3dtest.py            
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scipy/optimize/_lsq/least_squares.py:110: UserWarning: Setting `gtol` below the machine epsilon (2.22e-16) effectively disables the corresponding termination condition.
  warn("Setting `{}` below the machine epsilon ({:.2e}) effectively "
qt.qpa.openglcontext: Could not create NSOpenGLContext with shared context, falling back to unshared context.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/madcad/rendering.py", line 1099, in paintGL
    self.render()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/madcad/rendering.py", line 981, in render
    ViewCommon.render(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/madcad/rendering.py", line 712, in render
    self.uniforms['proj'] = proj = self.projection.matrix(w/h, self.navigation.distance)
ZeroDivisionError: division by zero
zsh: abort      python3 3dtest.py
```

**Comment by granludo** [comment]
yes, I move to that discussion, sorry
