### ISSUE TITLE
Subscript deletion not supported by `arrex.list.typedlist` in madcad v0.13

### ISSUE THREAD

**Issue by jimy-byerley** [jimy-byerley/pymadcad#47]
### Discussed in https://github.com/jimy-byerley/pymadcad/discussions/46

<div type='discussions-op-text'>

<sup>Originally posted by **EdwinSoft** September 19, 2022</sup>
Dear All,

Congratulations for this excellent project and I have a question, with version 0.12 of pymadcad the following code worked:

`
from madcad import *

ext = wire(Circle((O, -Y), 15, resolution=('div', 6)))
cir = wire(Circle((O, Y), 10))
surf = flatsurface([ext, cir])
show([surf])
`
![img](https://user-images.githubusercontent.com/5746631/191124792-c4897eb7-eed1-4366-8cc0-dab73897c9d3.png)
Trying the same code with version 0.13, I get an error:

> Traceback (most recent call last):
  File "/home/edwin/PycharmProjects/pymv13/main.py", line 5, in <module>
    surf = flatsurface([ext, cir])
  File "/home/edwin/PycharmProjects/pymv13/venv/lib/python3.10/site-packages/madcad/generation.py", line 401, in flatsurface
    m = triangulation.triangulation(web(outline), normal)
  File "/home/edwin/PycharmProjects/pymv13/venv/lib/python3.10/site-packages/madcad/mesh/conversions.py", line 63, in web
    pool.mergeclose()
  File "/home/edwin/PycharmProjects/pymv13/venv/lib/python3.10/site-packages/madcad/mesh/container.py", line 73, in mergeclose
    self.mergepoints(merges)
  File "/home/edwin/PycharmProjects/pymv13/venv/lib/python3.10/site-packages/madcad/mesh/web.py", line 85, in mergepoints
    del self.edges[j:]
NotImplementedError: Subscript deletion not supported by arrex.list.typedlist

Process finished with exit code 1

did anything change in version 0.13? or how should I modify the code to make it work?

Ubuntu 22.04
Python 3.10 </div>

The support for item deletition has not been released yet in [arrex](https://github.com/jimy-byerley/arrex) (one of the dependencies of madcad) at the moment (in arrex v0.4.2). But it is on the development branch.  It seems I released madcad v0.13 a bit too soon '^.^

**Comment by jimy-byerley** [comment]
fixed in latest release `v0.13.1`
